const CONSTANTS = {
  BALL_RADIUS: 10,
  PADDLE_HEIGHT: 10,
  PADDLE_WIDTH: 75,
  BRICK_ROW_COUNT: 5,
  BRICK_COLUMN_COUNT: 3,
  BRICK_WIDTH: 75,
  BRICK_HEIGHT: 20,
  BRICK_PADDING: 10,
  BRICK_OFFSET_TOP: 30,
  BRICK_OFFSET_LEFT: 30,
};

export default CONSTANTS;
